# Generated by Django 2.0.3 on 2018-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepanel',
            name='answer_box',
            field=models.TextField(verbose_name='content'),
        ),
    ]
