# Generated by Django 2.0.3 on 2018-04-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0002_auto_20180425_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('created',)},
        ),
    ]
