# Generated by Django 2.0.3 on 2018-04-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0003_auto_20180426_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmpmessage',
            options={'ordering': ('created',)},
        ),
    ]
