# Generated by Django 2.0.3 on 2018-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0004_auto_20180430_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepanel',
            name='answer_txt',
            field=models.TextField(blank=True),
        ),
    ]
