# Generated by Django 2.0.3 on 2018-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0005_messagepanel_answer_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepanel',
            name='ans_choice',
            field=models.TextField(choices=[('answer_this_wk', 'this_week'), ('answer_this_wk<18', 'this_week<18'), ('answer_mr_this_wk', 'mr_this_week'), ('answer_ms_this_wk', 'ms_this_week'), ('answer_next_wk', 'next_week'), ('answer_next_wk<18', 'next_week<18'), ('answer_mr_next_wk', 'mr_next_week'), ('answer_ms_next_wk', 'ms_next_week'), ('answer_other_term', 'other_term'), ('answer_other_term_mr', 'mr_other_term'), ('answer_other_term_ms', 'ms_other_term'), ('answer_office', 'office'), ('invitation_m_orday', 'inv_m'), ('invitation_m_wknday', 'inv_m_wknd'), ('invitation_f_orday', 'inv_f'), ('invitation_f_wknday', 'inv_f_wknd'), ('invitation_mr_orday', 'inv_mr'), ('invitation_mr_wknday', 'inv_mr_wknd'), ('invitation_ms_orday', 'inv_ms'), ('invitation_ms_wknday', 'inv_ms_wknd'), ('invitation_scnd', 'inv_rptd'), ('invitation_mr_scnd', 'inv_mr_rptd'), ('invitation_ms_scnd', 'inv_ms_rptd')], default='ans_this_wk'),
        ),
    ]
